### ISSUE TITLE
Getting error request while running the script

### ISSUE THREAD

**Issue by biraja72** [himoacs/iex_data#1]
I am new to python. Installed Pandas. Still while running the script, getting the following error:

C:\>python C:\IEX\iex_data.py
Traceback (most recent call last):
  File "C:\IEX\iex_data.py", line 11, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request

I am running at night which is after hours of stock exchnages. Please let me know it is due to time or I am missing something in Python.

Thanks,
Biraja

**Comment by himoacs** [comment]
It's complaining that you don't have the 'request' module. 

Install the module and then run the code again.

You can install it by running 'pip install request'

**Comment by biraja72** [comment]
C:\>pip install request
Requirement already satisfied: request in c:\python27\lib\site-packages

C:\>python C:\IEX\iex_data.py
Traceback (most recent call last):
  File "C:\IEX\iex_data.py", line 11, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request

I already did that. But still get the same error.
Any other suggestion will be appreciated.

Thanks,
Biraja

**Comment by reidwilson** [comment]
Yeah, I'm currently having the same issue.

**Comment by himoacs** [comment]
Which python version are you using?

Take a look at this thread which should answer your question: https://stackoverflow.com/questions/31601238/python-2-7-10-error-from-urllib-request-import-urlopen-no-module-named-request

**Comment by biraja72** [comment]
I have Python 2.7.14
Let me try above suggestion or I will use Python 3.0
Thanks.
Biraja
